version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysql_database
    restart: always
    volumes:
      - ./db/noteAppDb/init.sql:/docker-entrypoint-initdb.d/0_init.sql
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=noteAppDb
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=root
    logging: 
      driver: none
    ports:
      - 8080:80

