version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysql_database
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    restart: always
    volumes:
      - ./db/noteAppDb/init.sql:/docker-entrypoint-initdb.d/0_init.sql
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=noteAppDb
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      - client
      - server

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=root
    logging: 
      driver: none
    ports:
      - 8080:80

  client:
    build: resources/noteapp
    container_name: client
    command: ["npm", "start"]
    volumes:
      - ./resources/noteapp:/frontend
      - ./resources/noteapp/node_modules:/frontend/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'

  server:
    build: app
    container_name: server
    command: ["flask", "run", "--host=0.0.0.0"]
    volumes:
      - ./app:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    ports:
      - "5000:5000"
